# -*- mode: ruby -*-
# vi: set ft=ruby :

# Helper for host configuration - 32 or 64 bits systems
require './helper/core'
require './helper/utils'
require './helper/config'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder "../app", "/home/vagrant/app", create: true
  config.vm.synced_folder "../", "/home/vagrant/linc-api", create: true

  # Use an Ubuntu box based in the host arch
  arch = Vagrant::Util::Platform::bit64? ? 64 : 32
  config.vm.box = "ubuntu/trusty#{arch}"

  # Ports for services and api in development mode - 5000 for heroky deploy
  config.vm.network :forwarded_port, guest:  5000, host: 5000 # API Port
  config.vm.network :forwarded_port, guest: 27017, host: 27017 # MongoDB
  config.vm.network :forwarded_port, guest: 8081, host: 8081 # MongoDB Adimin Dev Purposes
  config.vm.network :forwarded_port, guest: 7081, host: 7081 # MongoDB Adimin Dev Purposes


  config.vm.network :private_network, ip: "192.168.100.10"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/app", "1"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/linc-api", "1"]
    vb.customize ["modifyvm", :id, "--memory", "1024"]
  end

  # Provision without puppet or cheff, using shell scripts
  config.vm.provision :shell, path: "./provision/ubuntu_provision.sh"

  # X11 over ssh
  config.ssh.forward_x11 = true
end
