# Copyright(C) Venidera Research & Development, Inc - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential
# Written by Rafael Giordano Vieira <rafael@venidera.com>

# A workflow for building, testing and deploying applications
name: CI

on:
  # Trigger the workflow on push
  push:
    # Push events on branches develop and master
    branches: [develop, master]
    # Anytime a path name matches, the workflow will not run
    paths-ignore: ['README.md']
  # Trigger the workflow on pull request
  pull_request:
    # Pull request events on branches develop and master
    branches: [develop, master]
    # Anytime a path name matches, the workflow will not run
    paths-ignore: ['README.md']

# Typed pipeline variables declared at the top level of a configuration.
# Users can pass parameters into their pipelines when triggering a new run.
env:
  IMAGE_NAME: venideraco/linc-api

# The basic units of work in a run
jobs:
  deploy:
    # Job name
    name: Deploying
    # Primary machine where all commands run
    runs-on: ubuntu-latest
    steps:
      # Used to check out source code to the configured path
      - name: Check out source repository
        uses: actions/checkout@v2
      # Logging in to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # Building the Docker image
      - name: Build the Docker image
        run: |
          docker build \
            --build-arg=API_PORT='${{ secrets.API_PORT }}' \
            --build-arg=ALLOWED_EMAILS='${{ secrets.ALLOWED_EMAILS }}' \
            --build-arg=API_URL='${{ secrets.API_URL }}' \
            --build-arg=APP_URL='${{ secrets.APP_URL }}' \
            --build-arg=ATLAS_DB='${{ secrets.ATLAS_DB }}' \
            --build-arg=COOKIE_SECRET='${{ secrets.COOKIE_SECRET }}' \
            --build-arg=CVREQ_TIMELIMIT='${{ secrets.CVREQ_TIMELIMIT }}' \
            --build-arg=CVSERVER_URL='${{ secrets.CVSERVER_URL }}' \
            --build-arg=CVSERVER_URL_IDENTIFICATION='${{ secrets.CVSERVER_URL_IDENTIFICATION }}' \
            --build-arg=CVSERVER_URL_RESULTS='${{ secrets.CVSERVER_URL_RESULTS }}' \
            --build-arg=CV_APIKEY='${{ secrets.CV_APIKEY }}' \
            --build-arg=CV_PASSWORD='${{ secrets.CV_PASSWORD }}' \
            --build-arg=CV_USERNAME='${{ secrets.CV_USERNAME }}' \
            --build-arg=EMAIL_FROM='${{ secrets.EMAIL_FROM }}' \
            --build-arg=MONGODB_URI='${{ secrets.MONGODB_URI }}' \
            --build-arg=MONGOLAB_URI='${{ secrets.MONGOLAB_URI }}' \
            --build-arg=REDISCLOUD_URL='${{ secrets.REDISCLOUD_URL }}' \
            --build-arg=REDIS_URL='${{ secrets.REDIS_URL }}' \
            --build-arg=S3_ACCESS_KEY='${{ secrets.S3_ACCESS_KEY }}' \
            --build-arg=S3_BUCKET='${{ secrets.S3_BUCKET }}' \
            --build-arg=S3_SECRET_KEY='${{ secrets.S3_SECRET_KEY }}' \
            --build-arg=S3_URL='${{ secrets.S3_URL }}' \
            --build-arg=S3_URL_EXPIRE_SECONDS='${{ secrets.S3_URL_EXPIRE_SECONDS }}' \
            --build-arg=SMTP_PASSWORD='${{ secrets.SMTP_PASSWORD }}' \
            --build-arg=SMTP_PORT='${{ secrets.SMTP_PORT }}' \
            --build-arg=SMTP_SERVER='${{ secrets.SMTP_SERVER }}' \
            --build-arg=SMTP_USERNAME='${{ secrets.SMTP_USERNAME }}' \
            --build-arg=TOKEN_SECRET='${{ secrets.TOKEN_SECRET }}' \
            --build-arg=TZ='${{ secrets.TZ }}' \
            --tag ${IMAGE_NAME}:${GITHUB_REF##*/} .
      # Publishing image to DockerHub
      - name: Publish the Docker image into DockerHub
        run: docker push $IMAGE_NAME:${GITHUB_REF##*/}
